# install Nginx using Ansible
# Start and Enable Nginx
# Check the status of Nginx
# Collect host information
- name: Setup nginx server on myserver list (host group)
  hosts:
    - devservers
  become: true
  tasks:
    # 1. インストール（Ubuntu用にaptモジュールへ変更）
    - name: Install the latest version of nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    # 2. 起動と自動起動有効化（1つのタスクにまとめられます）
    - name: Start and Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    # 3. バージョン取得（registerとchanged_whenを追加）
    - name: Get nginx Installed version
      ansible.builtin.command: nginx -v
      register: nginx_version
      changed_when: false

    # 4. nginxのステータスを取得（registerとchanged_whenを追加）
    - name: Get status of nginx service
      ansible.builtin.command: systemctl status nginx
      register: nginx_status
      changed_when: false

    # 5. ユーザー新規作成
    - name: Create new user
      user: 
        name: newuser
        group: users
        createhome: yes
        shell: /bin/bash
      register: user_add

    # 6. ssh接続の公開鍵の設定
    - name: Add authorized key for new user
      authorized_key: 
        user: newuser
        key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"
      register: key_add

    - name: Print add user key
      debug: 
        msg: "ユーザー作成とキー登録に成功しました"
      when: user_add.changed
      when: key_add.changed
