:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Docker

== ビルドコンテキスト

* Dockerイメージを作るときのファイルやディレクトリの範囲 +
※ ただし、ビルドコンテキスト内にdockerfileが存在してもイメージがうまく作れない場合もある。そこで、dockerfileは"-f"で指定する。

[source]
----
# (-f)でdockerfileのパス指定
docker image build -f <dockerfileのパス> <ビルドコンテキスト>

# 実行例(docker-lecture/docker/dockerfile)
docker image build -f docker/dockerfile .
----


== カスタムイメージ

=== COPY

* Dockerイメージをbuildする際に、ホストマシンにあるファイルやディレクトリをDockerイメージ内の指定したパスにコピーできる
* 既存で存在しないディレクトリの直下にCOPY指定する場合、コンテナを作成する際に自動的にディレクトリは作られる +

.COPY記述例
[source,DCL]
----
FROM ubuntu:20.04

RUN apt update
RUN apt install -y curl

# ファイルコピー
COPY ./hello.txt /app/
----

=== CMD(Dockerfile内)

* コンテナ実行時のデフォルトコマンドを設定する
* dockerdfile内で記述 +
※ dockerfileで１度しか使えない。複数のCMDが存在した場合、最後に記述されたCMDのみ有効となる。

* パラメータはいくつでも記述できる

CMD記述例
[source,DCL]
----
FROM ubuntu:20.04

CMD ["echo","Hello, Docker!"]
----

=== ★ WORKDIR

* RUNやCMDなどの作業ディレクトリを指定する +
※ 未指定の場合、"/"が作業ディレクトリになっている。

* コンテナにbashでアクセスした際のカレントディレクトリでもある

.WORKDIR記述例
[source, DCL]
----
FROM ubuntu:20.04

# 1.txt
# /app/mk_dir/2.txt
# /app/3.txt

RUN touch 1.txt
WORKDIR /app/my_dir
RUN touch 2.txt
WORKDIR ..
RUN touch 3.txt

CMD ["bash"]
----


=== ★ .dockerignoreファイル

* .dockerignoreに指定したファイルやディレクトリをビルドコンテキストから除外できる +
※ ビルドコンテキスト内に.dockerignoreファイルを作成する

* build imageに含ませたくないものを入れる
* .dockerignoreには容量の大きいファイルや機密情報を含んだ公開したくないファイルを記述することが多い

[source]
----
# 指定のファイルサイズのファイルを作成
truncate -s 500m <ファイル名>
----


=== イメージレイヤー(階層)

* イメージの変更差分がレイヤーとして保存される
* レイヤーが変更差分として保存されるおかげで、以前に実行されたbuildがキャッシュされ、実行時間の短縮につながっている
* イメージ作成後にdockerfileに追加する可能性がある場合にはあえてレイヤー構造を細かくすることで、追加していくときにbuild時間を短縮することができる

----
# イメージレイヤーの確認
docker image history <イメージ名>

# キャッシュなしでbuild
docker image build --no-cache <ビルドコンテキストパス>
----

=== イメージ容量(縮小)

* イメージレイヤーの層が減ることで容量が小さくなる +
※ イメージ容量が小さくなっても、イメージ作成にかかる時間が短くなるとは限らない

* レイヤー構造が少ない＝イメージ容量が小さい

.レイヤー階層別記述例
[source, DCL]
----
# イメージレイヤー(多)
FROM ubuntu:20.04

RUN apt update
RUN apt install -y curl
RUN apt install -y vim 
CMD ["bash"]

# イメージレイヤー(小)
FROM ubuntu:20.04

RUN apt update && apt install -y curl vim
CMD ["bash"]
----

== ★ 変数定義(Dockerfile内)

ENV:: イメージ作成とコンテナの両方で有効な変数、一度に複数個定義することが可能

ARG:: イメージ作成時のみ有効な変数、コンテナ実行時に影響しない +
※ build時限定の使い捨て変数

.変数定義の利点
[source, DCL]
----
# ❌ 悪い例（バージョンが変わるたびに3箇所書き換える必要がある）
RUN wget https://example.com/software-1.2.3.tar.gz
RUN tar -xvf software-1.2.3.tar.gz
WORKDIR /opt/software-1.2.3

# ⭕ 良い例（1行目を書き換えるだけで全てに反映される）
ARG APP_VERSION=1.2.3
RUN wget https://example.com/software-${APP_VERSION}.tar.gz
RUN tar -xvf software-${APP_VERSION}.tar.gz
WORKDIR /opt/software-${APP_VERSION}
----

.ENV,ARG 記述例
[source, DCL]
----
FROM ubuntu:20.04

ARG message_arg="Message Arg"
ENV message_env="Message Env"

RUN echo "$message_arg" > message_arg.txt
RUN echo "$message_env" > message_env.txt

CMD ["bash"]
----

----
# build時に値格納
docker image build --build-arg <変数名>="<値>" .
----


== マルチステージビルド

* マルチステージでイメージ作成することでイメージサイズを軽量にできる

* マルチステージビルドを使うときは、コンパイルや翻訳に必要な言語・フレームワークを利用してイメージを作成するとき

* Dockerfileを開発・本番といった環境ごとで分けられる +
※ １つのDockerfileで管理可能

=== マルチステージビルドでイメージサイズ軽量

* 以下の記述例では、最終的なベースイメージがgccかubuntuかで大きく異なった

.シングルとマルチステージビルドの違い記述例
[source, DCL]
----
# シングル
# gccをベースイメージで作成
FROM gcc:12.2.0 AS compiler
WORKDIR /app
COPY ./hello.c .
RUN gcc hello.c
CMD ["./a.out"]
----

----
# マルチ
# ubuntuをベースイメージで作成
# "AS <ステージ名>"でステージに名前を付けることができる。※ デフォルトでは一番上から"0"の順番がつけられている。
FROM gcc:12.2.0 AS compiler
WORKDIR /app
COPY ./hello.c .
RUN gcc hello.c


FROM ubuntu:20.04
WORKDIR /app
# "--FROM="でcopy元となるステージを指定している
COPY --from=compiler /app/a.out .
CMD ["./a.out"]
----

=== 環境別イメージ作成

* 共通部分は共有でき、環境依存処理部分で分離して、各々の環境Dockerイメージを作成できる
* EROMでステージ名を指定することで、共通部分を取得して実行できる
* ステージ名は基本「小文字」のみで書く

.環境別Dockerfile記述例
[source, DCL]
----
FROM ubuntu:20.04 AS base
RUN apt update 
CMD ["sh", "-c", "echo My name is ${my_name}"]


# FROMでステージを参照して環境ごとにDockerイメージを変える
FROM base AS development
ENV my_name=TEST

FROM base AS production
ENV my_name=Bob
----

----
# 環境別にDockerイメージを作成する際
docker image build --taerget <ステージ名> <ビルドコンテキスト>
docker image build --target development .
----



== その他

Docker Engine:: Dockerを動かすためのシステム全体像(パッケージ)。dockerCLI,API,Demonを含んだ総称。
Docker Demon:: Docker Engineの中に存在する１つのプログラム。コンテナの生成、実行、停止、イメージのダウンロードなどを担っている。
REST API:: システム同士がインターネットを通じてデータをやりとりする際のお約束
