:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Docker

== バインドマウント

バインドマウント:: ホストマシン側の任意ディレクトリとコンテナ側の任意ディレクトリを同期させる方法
* ホストマシン側とコンテナ側の双方から変更ができるため手軽 +
※ ボリュームと違う点は、ホストマシン側から変更を加えられること

----
# バインドマウントの同期させてコンテナ起動
docker container run -v <ホスト側絶対パス：コンテナ側絶対パス> <イメージ名>

# ボリュームバージョン
docker container run -v <volume名：コンテナ側絶対パス> <イメージ名>

# $(pwd)でパス指定を簡易化
docker container run -v <$(pwd)/my_dir：コンテナ側絶対パス> <イメージ名>
----
* 絶対パスを毎回入力するのは大変なので、 #$(pwd)# と記述することでパスの入力を簡易的にできる

.バインドマウントとボリュームの違い
[options="hesder"]
|===
|項目       |バインドマウント（Bind Mounts）            |ボリューム（Volumes）
|主な主戦場 |開発環境（ローカル）                       |本番環境（ステージング・本番）
|主な用途   |ソースコードの同期、設定ファイルの読み込み |データベースのデータ永続化、ログの保存
|管理の主体 |ユーザー（ホスト側の絶対パスを指定）       |Docker（Dockerが専用領域を管理）
|使いやすさ |ホストからファイルを直接編集しやすい       |ホストからは中身が見えにくい（安全）
|===


== コンテナ接続

=== ホストとコンテナ

* コンテナ内でwebサーバーが起動していたとしても、外部のブラウザからは接続できない
* ホストマシンとコンテナをポート接続することでアクセスが可能となる

ポートマッピング:: ホスト側のポートとコンテナ側のポートをつなぐ仕組み
[opsions, header]
|===
|ブラウザから\http://123.123.123.1:3000にアクセスした場合 +
ブラウザ→ホストマシン(ポート3000番)→コンテナ(ポート80番)
|===

[source, bash]
----
# ホストとコンテナのポート紐づけ (-p)
docker container run -p <ホスト側ポート：コンテナ側ポート> <イメージ名>
# 実行例
docker container run -v 3000:80 nginx
----

 
== Dockerネットワーク

* コンテナ同士を一つネットワークという枠に括ることで、そのネットワーク内のコンテナ間で通信することができる
* 各ネットワーク同士は通信することができないため、不要なコンテナ同士の通信を防ぐこともできる
* 現在は役割ごとにコンテナを作ることが主流であるため、Webアプリやデータベースごとでコンテナを立ち上げている

.Dockerネットワークコマンド一覧
[source, bash]
----
# Dockerネットワークの一覧表示
docker network ls 

# Dockerネットワークの詳細表示
docker network inspect <ネットワーク名>

# 新規brigeネットワーク作成(任意名)
docker network create <任意ネットワーク名>

# 指定したネットワークにコンテナを追加
docker container run --network <ネットワーク名> <イメージ名>
----

brigeネットワーク:: デフォルトDockerネットワーク
* コンテナを作成する際、Dockerネットワークを指定しない場合は「brige」に位置づけられる

* コンテナのIPアドレス： `docker network inspect <ネットワーク名>` から確認できる

=== Dockerネットワーク内名前解決

* Dockerネットワーク内で名前解決する際、新しくネットワークを作る必要がある +
※ #デフォルトのbrigeネットワークには名前解決の機能はない。# 

[source]
----
# 自分作成したネットワーク内で名前解決　〇
root@aa2ef318344f:/# curl http://my_nginx2
<!DOCTYPE html>
<html>
<head>
~
</body>
</html>

# デフォルトのbtigeネットワークの場合は名前解決　×
root@915f8e553142:/# curl http://my_ubuntu1
^C
root@915f8e553142:/#
----



== その他
