:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Docker

== Dockerとは

* コンテナ仮想化技術を使って、アプリケーションを開発・配置・実行するための隔離された環境を提供ツール +
※ DockerはホストOSとコンテナの仲介役。

=== Docker engine

* Dockerの核心となる技術（本体）
* コンテナを作る、動かす、管理する等のすべての処理を担っている


.Docker engine install
[source]
----
sudo apt remove $(dpkg --get-selections docker.io docker-compose docker-compose-v2 docker-doc podman-docker containerd runc | cut -f1)

# Add Docker's official GPG key:
sudo apt update
sudo apt install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

sudo apt update

sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo systemctl status docker

sudo systemctl start docker

sudo docker run hello-world
----
* 参考元URL:https://docs.docker.com/engine/install/ubuntu/


.非rootユーザーでのDocker管理（利用）
[source]
----
# グループ作成
sudo groupadd docker

# ユーザーをdockerグループに追加する
sudo usermod -aG docker $USER

# sudo権限なしでdockerコマンドが実行できるか確認
docker run hello-world
----
* 参考元URL:https://docs.docker.com/engine/install/linux-postinstall


=== Docker run

* Dockerのイメージからコンテナ立ち上げ、起動までを行うコマンド
* `sudo docker run hello-world`:Dockerを動かす最終確認コマンド


== コンテナ

* PCやサーバ上で隔離され干渉されない環境 +
※ コンテナの中に小さなPCが入っているイメージ。


=== コンテナのメリット

* ホストOS(windos,macOS)とコンテナ側でそれぞれの違ったソフトウェアを導入できる
* ホストOS上に複数コンテナを作ることができる
* コンテナごとの干渉もない
* コンテナはホストOS間の移動も容易

=== コンテナのライフサイクル

* Created(作成)　→　up(起動)　→　Exited(停止)


== Dockerイメージ

* コンテナに必要なソフトウェア・環境変数・設定などの情報が入っている +
※ コンテナの定義（型）
* Dockerイメージからコンテナを作る
* Dockerイメージは変更不可な静的なテンプレート
* DockerイメージのTagは、各バージョンやディストリビューションで分けられている

=== Dockerイメージの入手方法

. dockerhubから入手する
. dockerfile(設計書)から自分仕様のDockerイメージを作成する

Dockerhub:: Dockerイメージを登録・配布するサイト「https://hub.docker.com/」


=== Dockerイメージコマンド

[source]
----
# イメージのダウンロード
docker image pull <イメージ名>
docker image pull <イメージ名:tag>

# ローカルマシンに存在するイメージ一覧表示
docker image ls

# 全イメージ一覧表示
docker image ls -a

# イメージの削除
docker image rm <イメージ名>

# イメージ一括削除(名前なしのみ)
docker image prune
----

== コンテナへのアクション

=== コンテナの作成と実行

[source]
----
# イメージからコンテナ作成し起動する
docker container run <イメージ名>

# ローカルマシンに存在するコンテナ一覧表示
docker container ls

# 起動していないコンテナもすべて表示される ( -a )
docker container ls -a
----
※ dockerイメージがない状態でコンテナ作成すると自動でイメージがダウンロードされる


=== コンテナの停止と再起動

[source]
----
# 起動中コンテナの停止
docker container stop <コンテナ名かID>

# コンテナの再起動(upにする)
docker container restart <コンテナ名かID>

# コンテナのログ確認
docker container logs <コンテナ名かID>
----

=== コンテナの削除・一括削除・自動削除

[source]
----
# 停止済みコンテナ指定削除(Exted状態)
docker container rm <コンテナ名かID>

# 停止済みコンテナ一括削除
docker container prune

# コンテナ実行後自動削除 ( --rm )
docker container run --rm <イメージ名>

# 動作中コンテナ強制削除(up状態) 
docker container rm -f <コンテナ名>
----


=== コンテナをbashで操作

[source]
----
# (-i,--interactive):コンテナの標準入力口をopenな状態にする→これがないと、プロンプトから入力した実行がコンテナに届かない。
docker container run -i <イメージ名>

# (-t,--tty):コンテナ側をターミナル画面を表示される→これがないと、プロンプトやテキストカラーなどが出ない。
docker container run -t <イメージ名>

# (-it):
docker container run -it <イメージ名>
----

=== 任意コマンドに変更(コンテナが実行する)

* 各Dockerイメージにはデフォルトで設定されているコマンドがある +
例：ubuntu:bashコマンド

[source]
----
# Dockerイメージの詳細情報を表示
docker image inspect <イメージ名>

# イメージからコンテナを起動して任意のコマンドを実行させる
docker container run -it <イメージ名> <任意コマンド>
# 実行例

# up状態のコンテナに任意のコマンドを実行させる(execute=実行する)
docker container exec <コンテナ名> <任意コマンド>
# exted状態から行う場合
docker container restart <コンテナ名>
docker container exec <コンテナ名> <任意コマンド>
----

=== コンテナ名の指定

[source]
----
# 任意のコンテナ名に指定 ( --name )
docker container run --name <任意のコンテナ名>　<イメージ名>
----
 
=== フォアグラウンド、デタッチドモード

* デタッチドモード＝バックグラウンド

[source]
----
# デタッチドモードでコンテナ実行 ( -d )
docker cotanier run -d <イメージ名>
docker container exec -d <コンテナ名>

# デタッチ→フォアグラウンド
docker container attach <コンテナ名>
----

== DockerfileからDockerイメージ作成

=== Dockerfileの書き方

※ コンテナを直接カスタマイズした場合持ち運びができない。あくまで持ち運べるのはDockerイメージ

* 大文字で命令を記述
* 命令文に対してパラメータを記述

[source]
----
# Dockerfileからイメージ作成
# <ディレクトリパス>にはdockerfileが置いてあるパスを指定する
docker image build <ディレクトリパス>
----

.実行したdockerfile
[source]
----
FROM ubuntu:20.04

RUN apt update
RUN apt install -y curl
----

=== イメージ名の変更

[source]
----
# イメージ名の変更 ( -t )
docker image build -t <任意のイメージ名> <ディレクトリパス>
----


