:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Ansible

== セクション１：コース概要
* IaC :サーバやネットワークの設定を設定ファイルに書き込んで自動化する手法


== セクション：IaC概要

=== IaC
* インフラ構築をコードを用いて行う方法

=== 手作業による課題
* 作業工数増大
* 作業品質低下 +
※クラウド上でのインフラ構築も例外ではない

=== コードによる作業内容と効果
* 定義ファイル作成やコマンド実行による作業内容軽減
* 作業工数の削減
* コードチェックにより設定ミス削減や作業品質向上

=== Iac ツール

.IaCツール
|===
|#Packer#: +
 コードはJson,HCL、マシン作成のイメージまで行う +

|#Terraform#: +
 コードはHCL、マシンイメージを指定することでマシンイメージに沿った構築を行う +
 強み: インフラ構築、インフラメンテナンス、アプリケーション初期設定

|#Ansible#: +
 コードはplaybookという単位にまとめられYAML形式の設定ファイルに記述し、設定ファイルをコマンド実行することでインフラ構築を行う +
 特徴: 設定ファイルにインフラの作成手順を記述する +
 強み: インフラメンテナンス、アプリケーション初期設定、アプリケーションメンテナンス +
 Terraformは作成手順を自動で設定してくれる点が違う +
 ※Ansibleはファイル内の処理を上から順番に実行するのみであるため、リソースの依存関係を意識する必要がある +


|#Puppet#: +
 オープンソースであり、コードはPuppet DSL、Terraform同様にインフラの最終状態を記述する +
 強み: Ansible同様にインフラメンテナンスに強い +
 弱み: 利用するためには構築対象のサーバにソフトウェアをインストールする必要があるため手間がかかる

|#Chef#: +
 オープンソース、コードはRuby DSL、Ansible同様作成手順を記述する +
 強み: インフラメンテナス、アプリケーション初期設定、アプリケーションメンテナンス +
 弱み: Puppet同様にインストールが必要
|===


== セクション３：IaC ハンズオン（理論）

=== Ansibleの仕組み
マスター（マネジメントノード）:: Ansibleのツールがインストールされたマシン
ターゲット（リモートホスト）:: 変更対象となるサーバ

|===
|ステップ１ +
 * インベントリを元に、対象となるターゲットの情報（IPアドレス等）を取得する +
 * playbookを元に、対象のターゲットに対して行うメンテナンス内容を取得する
|ステップ２ +
 * ステップ１で取得した情報を元に、メンテナンスを行う

|===
#※Ansibleではハードウェアの情報は取得できるが、設定（メモリ使用量等）の変更はできない# +
冪等性(べきとうせい):: 同じ操作を何度繰り返しても、同じ結果が得られる性質

* Ansibleではマスターとターゲットのファイルの状態を確認し、同じ内容の場合には処理をスキップする +
※この仕組みがあるため、リネームやタイムスタンプを気にする必要がない点が冪等性のメリット

==== インベントリ
インベントリ:: 対象ターゲットのホスト名やIPアドレスを管理するためのファイル
* `Hostsファイル`: デフォルトインベントリ、通常DNSサーバーを使用せずに名前解決をするために使用する
* `インベントリファイル`: 拡張子を任意で使用できる、Ansible個別でターゲット管理できるのがメリット +
※ サーバーごとの役割別だけでなく、"本番環境"、"開発環境"といった環境ごとでもグループが作れる

==== playbook
playbook:: 各ターゲットに対して行うメンテナンス内容を記述したファイル#


.playbookの作法
|===
|`サマリ部`: +
* playbookの概要（簡潔な内容）、メンテナンス対象のターゲットを定義
|`タスク部`: +
* メンテンナンス内容を定義 +
* メンテナンスの単位をタスクと呼び、複数のタスクを定義できる +
* 各タスクはメンテナンス内容に応じて使用するモジュールを使用し定義する
|`- name:` でリストとディクショナリーの組み合わせで直後に記載した構成をグループ化する
|===

==== yaml
* データを人間が読めるように表現するための言語
* より簡潔で可読性が高い
* 表現形式として、"リスト"と"ディクショナリー"の２つがある

|===
|構成要素
|`-`:リスト表現
|`:`:ディクショナリー表現
|`- 〇〇:`:リストとディクショナリーの組み合わせ
|`〇〇:`:このようなに要素の先頭に記述することでグループ化できる
|===

. yamlファイルの作法
.. リストを表すには、(-)を使用して各要素を指定する
.. ディクショナリーを表すには、キーと値を(:)で区切る
.. ラベル付けの際はインデントを使用して構造表現する
.. コメントを表すには、(\#)を使用する
.. 文字列を表すには(")(')で囲む
.. 真偽値を表すには、trueまたはfalse
.. 特殊文字にはエスケープシーケンスを使用する
.. 文字列を複数行で表すには、改行反映(\|)、改行なし(\>)を使用する

==== モジュール
モジュール:: 部品や工具、ライブラリはモジュールを集約した箱
標準モジュール:: Ansibleに標準搭載されており、Ansibleをインストールすると即利用できる
カスタムモジュール:: Ansibleに標準搭載されていない、独自に作成したモジュールをplaybookに読み込むことで使用できる +
※ AnsibleはPythonを内部で使用しているため、Pythonでカスタムモジュールを作成することが推奨されている +
ansible.cfg:: Ansibleの設定ファイル

==== ロール
ロール:: タスクを整理・分割する仕組み（機能） +
→ メリット:ロールが明確ならコードの修正を早く行うことができ、誤った修正リスクを軽減できる

|===
* ロール作成の手順
. タスク分割の基準を決める +
 基準として、<リソースの種類> <操作の種類>の２通りがある ※ プロジェクトで何を重視するかに応じて決める
. ロール名の付与 +
 各ロール（タスク）を実行する際に必要
. ロールを呼び出すためのplaybookを作成する +
 +
※ロールごとにファイルを作成
|===

==== Ansibleの出力結果の見方
* PLAY、TASK、PLAYRECAPの３つの項目で出力される
* `PLAY`:どのターゲットに対してplaybookを実行しているか出力
* `TASK`:plyabook内の各タスクごとに、タスク名と実行結果が出力される
* `PLAY RECAP`:plyabook全体のタスク実行結果のサマリーを出力

.タスク実行結果のステータス
|===
|ok : 正常に終了した(ターゲットに変化なし)
|changed : 正常に終了した(ターゲットに変化有り)
|skipped : タスクを実行しなかった
|failed : エラーが発生した
|===

.タスク実行後のステータス
|===
|ok : 正常に終了した数
|changed : 正常に終了したタスクのうち、状態が変更したタスクの数
|unreachable : 通信エラー起因で発生したエラー数
|failed : 通信エラー起因以外で発生したエラー数
|skipped : タスクを実行しなかった数
|rescued : rescueディレクティブを実行した数
|ignored : エラーが発生したが無視したタスク数
|===
ディレクティブ:: Ansibleで実行されるplaybookやタスクのこと
rescueディレクティブ:: エラー発生しても実行されるタスク

=== ハンズオンで使用するAWS サービス・ツール
Amazon EC2:: AWS上で仮想的なサーバーを構築するためのサービス +
※ EC2で作成したサーバーをEC2インスタンスと呼ぶ

Visual Studio Code:: コード記述エディタ、コードの補完や文法エラーチェックなどの便利な機能が備わっている

tera Term:: サーバーにSSH接続するためのクライアントソフト


