:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Ansible

== セクション４：ハンズオン実践

=== ★ ハンズオン１６：get_urlモジュール実施
* `dest:`:ターゲットサーバーのどこにファイルを配置するか、絶対パスを指定する
* `#get_url#`:URLからファイルをダウンロードするモジュール

|===
    # 8. URLからファイルをダウンロード +
    - name: Download download1-file.txt +
      #get_url:#  +
        url: \http://lcalhost/download-derectory/download-file.txt +
        dest: /home/ubuntu/ +
      register: file_download +
 +
    # 9.URLからファイルダウンロード結果出力 +
    - name: Print file download status +
      debug:  +
        msg: "ファイルダウンロードが成功しました" +
      when: file_download.changed 

|===

=== ★ ハンズオン１７：templateモジュール
* `template:`:既存の設定ファイルを元に、ファイル内容を変更した形でターゲット側に設定ファイルを作成できる
* templateモジュールを使って各サーバにファイルを配布するとき、元となるtamplateファイルに#".j2"#という拡張子を付けて保存する +
※ .j2 という拡張子を見かけたら、「Ansibleが実行時に中身を動的に書き換えてくれる、設定ファイルの『型枠（テンプレート）』だな」

|===
|★templateファイル内での決まりごと
|`#{\#\#}#` +
:templateファイル内でコメントを入力する際に使う
|`#{%<〇〇>%}#` +
:templateファイルの式記述形式 +
※式の中にif文やfot文、変数定義などを記述しルールを決める
|`#{{<変数名>}};#` +
:変数展開（templateファイル内） +
例：user {{ user_name }};
|===

|===
| playbook 記述
|    # templateモジュールの利用
    - name: Generete config file +
      template: +
        src: "tempmodule.conf.j2" +
        dest: "/home/ubuntu/tempmodule.conf" +
      vars: +
        access_log_path: /var/log/tempmodule/access.log
|===

|===
|templateファイル記述例
|{# tempmodule conf file. #} ←コメント行 +
{% set user_name = "tempmoduleuser" %} ←式の記述（変数定義） +
user {{ user_name }}; ←変数の展開 +
access_log {{ access_log_path }}; ←変数の展開（変数定義はplaybook内で記述） +
|===

=== ハンズオン１８：user モジュール（作成）
* `user:`:システム上のユーザーアカウントを管理するためのモジュール +
※ 新しいサーバーを構築する際、同時にユーザーアカウントも作成時に使用する +* `authorized_key:`:SSHの公開鍵を登録・管理するためのモジュール

|===
    # 5. ユーザー新規作成 +
    - name: Create new user +
      user:  +
        name: newuser +
        group: users +
        createhome: yes +
        shell: /bin/bash +
      register: user_add +
 +
    # 6. ssh接続の公開鍵の設定 +
    - name: Add authorized key for new user +
      authorized_key: +
        user: newuser +
        key: "{{ lookup('file', '~/.ssh/authorized_keys') }}" +
      register: key_add +
 +
    # 7. 出力確認 +
    - name: Print add user key +
      debug:  +
        msg: "ユーザー作成とキー登録に成功しました" +
      when: user_add.changed +
      when: key_add.changed +

|===

=== ハンズオン１９：user（group追加）
* `append:`:追加を意味するパラメータ

|===
    # 5.既存グループにユーザーを追加 +
    - name: Change user's belonging group +
      user: +
        name: newuser +
        group: adm +
        append: yes ←グループに追加することをOKしている +
|===
※ コマンドgroupsで確認できる

=== ハンズオン２０：user（削除）

|===
    # 5.既存ユーザーの削除 +
    - name: Delete user +
      user: +
        name: newuser +
        state: absent +
|===

=== ★ ハンズオン２１：setup モジュール
* `#setup:#`:OS情報やハードウェア、IPアドレス、メモリといったあらゆる詳細情報を自動で一括収集するモジュール
* `#gather_subset#`:setupモジュールのパラメータで、取得情報を指定できる +

|===
|gather_subsetの項目一覧
|all=すべての情報
|min=OS種類やバージョンなどの最小限情報
|hardware=CPUやメモリ,ディスクなど
|network=IPアドレスやMACアドレスなど
|virtual=対象サーバが仮想マシンかどうか
|===

|===
    # 5. ハードウェアとネットワーク情報取得と取得情報出力 +
    - name: Collect host information +
      setup: +
        gather_subset: +
          - "hardware" +
          - "netwark" +
      register: host_info +
 +
    # 6. 取得情報を出力
    - debug: +
        var: host_info ←取得した情報を出力

|===

=== ハンズオン２２：reboot モジュール
* `reboot:`:対象ターゲットの再起動を行うモジュール +
※ 再起動ではインスタンスのIPアドレスは変わらない

|===
    # 5. 再起動 +
    - name: Reboot +
      reboot: +
        msg: "rebooting the machine" ←再起動時にメッセージを表示する +
|===

=== ハンズオン２３：カスタムモジュール
* カスタムモジュールの最低限必要な構成要素 +
. ansibleモジュールのimportする
. importしたansibleモジュールの初期化する
. ansibleからパラメーターを取得する
. ansibleに処理結果を返す記述をする

* reモジュール：pythonで正規表現を使って文字列検索や抽出、置換などの処理が行うための標準ライブラリ
* モジュールのインスタンス：モジュールにパラメータを流して実際に動く状態にしたもの。=タスクと同じもの
* module.params:playbookから渡された引数（パラメータ）が格納されているpythonの辞書
* `メソッド`:関数と似ているが、特定のオブジェクト（データや変数）に紐づいている関数のこと +
※ 必ず#オブジェクト.メソッド()#のように、繋いで呼び出される
* lambda関数：pythonのみで作成できる関数 +
例：lambda <引数>: <処理内容> +

|===
#!/usr/bin/python3                                            ←pythonでのシェルスクリプト +
 +
import re                                                      ←**★reモジュールをimportしている** +
from ansible.module_utils.basic import AnsibleModule           ←basicというクラスからAnsibleModuleだけをimportする記述 +
 +
def main():                                                    ←main関数定義 +
 +
    module_args = dict(                                        ←dict=ディクショナリーオブジェクト作成関数 +
        input_file=dict(type='str', required=True) +
    ) +
    module = AnsibleModule(                                    ←**★Ansibleモジュールクラスのインスタンスを作成している。以下の二つの引数が必要** +
        argument_spec=module_args,                             ←モジュールが受け取る引数のルールを定義している。ここでは上で指定したmodule_aegsというルールを採用する +
        supports_check_mode=True                               ←モジュールに冪等性を採用するかしないか +
    ) +
 +
    input_file = module.params['input_file']                   ←**★ansibleから受け取った"input_file"という引数を"input_file"という変数に格納している** +
    with open(input_file, 'r') as f:                           ←変数input_fileに格納されたファイルを読み取り専用で開き、変数fに格納し自動で閉じるという命令文 +
        html = f.read()                                        ←前の処理で変数fに格納されたデータを読み取り、変数htmlに格納する +
 +
    # Convert all lowercase characters to uppercase            +
    html = re.sub(r'[a-z]\', lambda m: m.group(0).upper(), html) ←小文字から大文字に変換する支持を記述している +
 +
    # Save modified HTML to the same file +
    with open(input_file, 'w') as f:                           ←open関数でinput_fileを書き込み専用で開き上書きするようにしている +
        f.write(html)                                          ←変数htmlに格納されている文字列をファイルに上書きしている。（小文字から大文字） +
 +
    module.exit_json(changed=True, result=input_file) +
←**★module.exit_jsonというのは成功か終了の合図を送るメソッド。changedの時に黄色になる。resultは戻り値であるため、指定した値を実行後に返してくれる。** +
 +
if __name__ == '__main__':                                     ←pythonでスタート位置をハッキリさせるために使われる決まり文句 +
    main()                                                     ←main関数の呼び出し +
|===
* `#!/usr/bin/python3`:pythonのバージョンを環境にあったものにしておく必要がある
* カスタムモジュールを読み込むために、ansible.cfgファイルでライブラリのパスを指定しておくこと +
※ カスタムモジュールをライブラリの指定パス直下に置くことで読み込まれる +
* `#module_utils`:カスタムモジュールで使いまわせる「共通の関数やクラス」を置いておくための自作の共有ライブラリ置き場#

|===
    # 6. カスタムモジュール実行 +
    - name: Use custom module +
      custom_module: +
        input_file: "{{ html_path }}/index.html" +
      regidter: result +
 +
    # 7. カスタムモジュール結果出力 +
    - name: Print result +
      debug: +
        var: resul
|===
