:toc: left
:toc-title: [目次]
:toclevels: 3
:sectnums:

= Docker

== Docker Copose

=== コンテナ同士接続

depends_on(プロパティ):: DockerCompose.yamlでサービス間の起動順序を定義する際に用いる +
※ DBを起動した後にWebサーバーを起動したいときに使ったりする

[source]
----
# 強制的にイメージビルドを実行する(既存でイメージ作られていた際に行うことがある)
docker compose up --build
----

== ソフトウェア開発の流れ

|===
|開発(開発環境構築、開発、コミット)=VScode,github +
　↓ +
 CI(ビルド、テスト)=github Actions +
　↓ +
 CD(デプロイ)AWS,githubイメージレジストリ +
|===

[source]
----
# コンテナ一覧表示(ls同様)
Docker compose ps
----

.DockerCompose.yaml記述
[source, yaml]
----
services:
  api: 
    # コンテナ名を任意に設定
    container_name: api
    build: ./api
    ports: 
      - 8080:8080
    tty: true
    # compose内では相対パスでも良い。:cachedはオプションでより早く処理されるがデータの一貫性は少し低くなる
    volumes:
    - ./api:/workspace:cached

  web:
    container_name: web
    build: ./web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes: 
      - ./web:/workspace:cached
    depends_on:
      - api
----

=== VScodeからコンテナ接続

* compose.yaml内に、APIとWEBコンテナの記述しVScodeからどちらかに接続した時点で片方のコンテナも立ち上がっている

リバースプロキシ:: インターネットとWebサーバーの間に入り、クライアントの代わりにWebサーバーへアクセスを受け渡す「中継サーバー」

.dockercomposeファイルでのマルチステージ記述例
[source, yaml]
----
 web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes: 
      - ./web:/workspace:cached
    depends_on:
      - api
----

== github Actions

* GitHubが提供しているCI/CDの自動化プラットフォーム +
gitpushなどのアクションが起きた際に、あらかじめ決めていた処理が自動的に実行される

[source]
----
💻 開発環境 (WSL等)          ☁️ GitHub Actions          📦 GitHubレジストリ          🚀 本番サーバー
┌───────────────────┐        ┌─────────────────┐        ┌──────────────────┐        ┌─────────────────┐
│ コードを書く       │ ───►   │ Dockerイメージ  │ ───►   │  ghcr.io         │ ───►   │ docker pull     │
│ Dockerfileを作る  │ (push) │ を自動ビルドする │ (push) │ (イメージを保管)  │ (pull) │ してコンテナ起動 │
└───────────────────┘        └─────────────────┘        └──────────────────┘        └─────────────────┘
----


== その他

githubイメージレジストリ:: githubが提供しているコンテナイメージの保管庫

github Actions:: github上で何か(code pushなど)が起きたら、あらかじめ決めておいた処理(テストやビルド、デプロイなど)を自動で実行してくれる機能

AWS ECR:: Dockerhubのように好きなイメージをアップロードして保存しておけるサービス

AWS ECS:: コンテナ管理サービス

APIとWEBサーバーの違い:: webはwebページを表示するためのファイルを届ける、apiはアプリやシステムの裏側で必要とする「データ」だけを処理・返却する

Node.js:: 本来ブラウザの名kでしか動かなかったjavascriptを、PCやサーバー上でも動かせるようにした実行環境

init:: システムやプログラムが動き出す最初の一歩として実行される処理・コマンド(初期化、起動処理)

npm:: Node.jsで使われるパッケージ管理ツール


