# install Nginx using Ansible
# Start and Enable Nginx
# Check the status of Nginx
# Collect host information
- name: Setup nginx server on myserver list (host group)
  hosts:
    - devservers
  become: true

  tasks:
    # 1. インストール（Ubuntu用にaptモジュールへ変更）
    - name: Install the latest version of nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    # 2. 起動と自動起動有効化（1つのタスクにまとめられます）
    - name: Start and Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    # 3. バージョン取得（registerとchanged_whenを追加）
    - name: Get nginx Installed version
      ansible.builtin.command: nginx -v
      register: nginx_version
      changed_when: false

    # 4. nginxのステータスを取得（registerとchanged_whenを追加）
    - name: Get status of nginx service
      ansible.builtin.command: systemctl status nginx
      register: nginx_status
      changed_when: false

    - name: Read external variable file
      include_vars: vars.yaml

    # 5. コピー
    - name: Ansible copy file to remote server
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
          <meta charset="UTF-8">
          </head>
          <body>
          <h1>このページはcopyモジュールのcontentパラメータを使用してコピーしたページです！</h1>
          <a href="download-derectory/download-file.txt" download>download-file.txtをダウンロード</a>
          </body>
          </html>
        dest: "{{ html_path }}/index.html"
      register: file_copy

    # 7. ファイルコピーの結果出力
    - name: Print file copy status
      debug: 
        msg: "ファイルコピーが成功しましt"
      when: file_copy.changed

    # 8. URLからファイルをダウンロード
    - name: Download download1-file.txt
      get_url: 
        url: http://localhost/download-derectory/download-file.txt
        dest: /home/ubuntu/
      register: file_download

    # 9. URLからファイルダウンロード結果出力
    - name: Print file download status
      debug: 
        msg: "ファイルダウンロードが成功しました"
      when: file_download.changed

