name: Node.js Test Automation

on:
  push:
    branches: [ "main", "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: github_actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and Run test
      run: |
        npm ci
        npm test
